<?php

/**
 * This file is part of the authbucket/oauth2-php package.
 *
 * (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Perseids\OAuth2\Entity;

use AuthBucket\OAuth2\Model\ScopeManagerInterface;
use Perseids\OAuth2\Entity\AbstractEntityRepository;

/**
 * ScopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScopeRepository extends AbstractEntityRepository implements ScopeManagerInterface
{
}
